### PR TITLE
JP-3721: Simplify ModelContainer

### PR DESCRIPTION
**Pull request by emolter**
Helps to resolve [JP-3721](https://jira.stsci.edu/browse/JP-3721)

Helps to close [spacetelescope/jwst:8738](https://github.com/spacetelescope/jwst/issues/8738)

This PR enables the JWST ModelContainer to no longer inherit from DataModel  as part of an effort to make ModelContainer's usage narrower and easier to understand.

## Tasks
- [x] update or add relevant tests
- [x] update relevant docstrings and / or `docs/` page
- [x] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [x] [run `jwst` regression tests](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) with this branch installed (`"git+https://github.com/<fork>/stdatamodels@<branch>"`)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.feature.rst``: new feature
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.doc.rst``: documentation change
- ``changes/<PR#>.removal.rst``: deprecation or removal of public API
- ``changes/<PR#>.misc.rst``: infrastructure or miscellaneous change
</details>

### CODE REVIEW

**Comment by emolter** [comment]
[started jwst regtests here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1773/)

**Comment by braingram** [comment]
> This PR enables the JWST ModelContainer to no longer inherit from DataModel and to no longer require its own `save` method, as part of an effort to make ModelContainer's usage narrower and easier to understand.

I follow the changes motivated by the inheritance change. Since `ModelContainer` is no longer a `JwstDataModel` subclass it won't enter:
https://github.com/spacetelescope/stdatamodels/blob/852c8d71a57d3c0f9f2eb1d12a7b89d77461a38a/src/stdatamodels/jwst/datamodels/util.py#L103-L105
by switching `list` to `Sequence` here:
https://github.com/spacetelescope/stdatamodels/blob/852c8d71a57d3c0f9f2eb1d12a7b89d77461a38a/src/stdatamodels/jwst/datamodels/util.py#L156-L162
`dm.open(container)` will do the same thing as before (call `ModelContainer(container)`).

I don't following the `no longer require its own save` bit. Is that just in reference to [AbstractDataModel.save](https://github.com/spacetelescope/stpipe/blob/ecd5d162be425c24db2498b34bcbaeccec4ac557/src/stpipe/datamodel.py#L47)?

**Comment by emolter** [comment]
> I don't following the no longer require its own save bit. Is that just in reference to [AbstractDataModel.save](https://github.com/spacetelescope/stpipe/blob/ecd5d162be425c24db2498b34bcbaeccec4ac557/src/stpipe/datamodel.py#L47)?
Yes, and it hasn't got anything to do with stdatamodels specifically, as you correctly point out.  I will remove it from the summary

**Review by braingram — APPROVED** [review]
LGTM.

**Comment by emolter** [comment]
regression tests passed.  @braingram I don't have permissions to request additional reviewers nor merge in this repository, feel free to do either at your convenience

**Pull request merged**
