### PR TITLE
JP-2113: Backwards compatibility and schema fixes

### PR DESCRIPTION
**Pull request by tapastro**
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn)

Closes #

This PR removes the attempt to save inverse models to the transforms when they exist. It also adds backwards compatibility for processing with simple linear transforms as well as second-order field-dependent transforms.

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [x] added relevant label(s)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
I don't completely understand all of the details, but if @tapastro says it works, I'm good with that!

**Comment by hbushouse** [comment]
There's a simple codestyle error that needs fixing. Also, has this been tested in concert with the corresponding jwst PR?

**Comment by tapastro** [comment]
> There's a simple codestyle error that needs fixing. Also, has this been tested in concert with the corresponding jwst PR?

Fixed the newline issue; code has been tested in tandem with (and is required by) https://github.com/spacetelescope/jwst/pull/7018

**Review by nden — APPROVED** [review]
LGTM

**Pull request merged**
