### PR TITLE
JP-2349: added v2/v3 columns to moving target position table schema

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-2349](https://jira.stsci.edu/browse/JP-2349)

Closes spacetelescope/jwst#6507

This PR addresses adding V2/V3 coordinates to the moving target position table schema, in order to provide position information for SLIT and COMPOUND aperture types.

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by hbushouse** [comment]
Keeping this in draft form until SDP adds the new columns to the table (in level-1b processing), which likely won't happen until DMS B11.0.

**Review by tapastro — APPROVED** [review]
LGTM

**Comment by tapastro** [comment]
Note: this PR breaks some JWST regression tests, see: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1662/testReport/junit/jwst.regtest/test_nircam_mtimage/_stable_deps__test_nircam_image_moving_target_kwds_with_mt_table_/

Will need to update our regression test data and truth data to accommodate new schema structure before the next stdatamodels release.

**Comment by RyleighDavis** [comment]
It looks like this update to the moving target schema is causing issues opening MAST files with JWST pipeline version 1.16. After updating the pipeline to versino 1.16, when attempting to open a moving target uncal file as a datamodel, I now get the error

**Comment by tapastro** [comment]
Hi @RyleighDavis , I've filed a workaround here: https://github.com/spacetelescope/stdatamodels/pull/329

If you're comfortable installing from the pull (or my branch), that should fix your issues. I think we should be able to get this merged and released in the next couple of days, pending any further issues discovered.

**Pull request merged**
