### PR TITLE
Added mrsptcorr ref file information to core.schema to support JP-3327

### PR DESCRIPTION
**Pull request by jemorrison**
This PR is needed to resolves [JP-3327](https://jira.stsci.edu/browse/JP-3327)

Closes #

This PR addresses adds the ref_file mrsptcorr to code file. This reference file is the MRS Point Source Correction reference file. This reference file is needed for JP-3327. 

**Checklist**
- [ ] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [x] added relevant label(s)

### CODE REVIEW

**Comment by jemorrison** [comment]
@braingram Can we get this merged soonish. I need for the JWST step spectral_leak

**Review by braingram — APPROVED** [review]
@jemorrison the changes in isolation look good to me. Is there a corresponding jwst PR? @hbushouse @tapastro any comments?

**Comment by jemorrison** [comment]
The corresponding JWST pr is https://github.com/spacetelescope/jwst/pull/8039

**Comment by jemorrison** [comment]
@hbushouse  Can I go ahead and merge this PR

**Review by hbushouse — APPROVED** [review]
Yep, looks OK to me.

**Pull request merged**
