### PR TITLE
Add cal_step status keyword for clean_flicker_noise

### PR DESCRIPTION
**Pull request by tapastro**
Addresses [JP-3639](https://jira.stsci.edu/browse/JP-3639)

This PR adds the cal_step keyword for the newly added step `clean_flicker_noise`.  

## Tasks
- [ ] update or add relevant tests
- [ ] update relevant docstrings and / or `docs/` page
- [ ] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] [run `jwst` regression tests](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) with this branch installed (`"git+https://github.com/<fork>/stdatamodels@<branch>"`)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.feature.rst``: new feature
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.doc.rst``: documentation change
- ``changes/<PR#>.removal.rst``: deprecation or removal of public API
- ``changes/<PR#>.misc.rst``: infrastructure or miscellaneous change
</details>

### CODE REVIEW

**Review by braingram — COMMENTED** [review]
Schema change looks good. Would you add a changelog fragment?

**Review by braingram — APPROVED** [review]
Thanks!

**Comment by tapastro** [comment]
💨 🏁

**Comment by melanieclarke** [comment]
Thanks @tapastro! I forgot this change would be needed.

**Pull request merged**
