### PR TITLE
JP-3449: Add TMEASURE keyword to core schema

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3449](https://jira.stsci.edu/browse/JP-3449)

Closes [spacetelescope/jwst#8036]

This PR addresses adding TMEASURE to the JWST core schema.

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [x] updated relevant milestone(s)
- [x] added relevant label(s)

### CODE REVIEW

**Review by braingram — APPROVED** [review]
Schema changes look good to me. Thanks for making this update!

Is there a jwst PR to populate and/or use the new keyword?

**Comment by emolter** [comment]
I am working on JP-3465 but it isn't ready yet; here's a [link to the draft PR](https://github.com/spacetelescope/jwst/pull/8212).

**Comment by hbushouse** [comment]
@braingram This keyword will be populated by SDP code during level-1b processing, just like all the other time-related keywords. There is an existing JSDP ticket to compute the value and populate it, and a JWSTKD ticket to add the definition to the official JWST keyword dictionary. So all bases are covered.

**Comment by hbushouse** [comment]
All the CI failures seem to be due to the same test "test_crds_selectors_vs_datamodel[miri]" and appear to be having a problem with model.meta.exposure.ngroups. No idea why this change would be causing that failure. I've checked the new lines in the core.schema.yaml lines closely and I don't see any syntax errors that would cause other failures in the schema.

**Comment by tapastro** [comment]
> All the CI failures seem to be due to the same test "test_crds_selectors_vs_datamodel[miri]" and appear to be having a problem with model.meta.exposure.ngroups. No idea why this change would be causing that failure. I've checked the new lines in the core.schema.yaml lines closely and I don't see any syntax errors that would cause other failures in the schema.

This was caused by a CRDS update that didn't have a matching datamodel update, addressed in #251.

**Review by hbushouse — APPROVED** [review]
Everything looks good now. All CI tests pass.

**Pull request merged**
