### PR TITLE
JP-3772: Add new DHS readout patterns to JWST schema

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3772](https://jira.stsci.edu/browse/JP-3772)

Closes spacetelescope/jwst#8854

This PR addresses adding new DHS readout patterns to the JWST schema.

## Tasks
- [ ] update or add relevant tests
- [ ] update relevant docstrings and / or `docs/` page
- [ ] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] [run `jwst` regression tests](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) with this branch installed (`"git+https://github.com/<fork>/stdatamodels@<branch>"`)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.feature.rst``: new feature
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.doc.rst``: documentation change
- ``changes/<PR#>.removal.rst``: deprecation or removal of public API
- ``changes/<PR#>.misc.rst``: infrastructure or miscellaneous change
</details>

### CODE REVIEW

**Review by braingram — APPROVED** [review]
LGTM. Thanks!

**Comment by emolter** [comment]
> It's possible that reference files will be generated using this readout pattern, so we should probably also update the keyword_readpatt and the keyword_preadpatt schemas.

done, lmk if this looks ok to you

**Comment by braingram** [comment]
Would you also start regtests with this branch?

**Comment by emolter** [comment]
[started here](https://github.com/spacetelescope/RegressionTests/actions/runs/11803632576)

**Pull request merged**
