### PR TITLE
remove deprecated_properties

### PR DESCRIPTION
**Pull request by braingram**
`deprecated_properties` appears to have been added to allow moving "properties" within a schema:
https://github.com/spacetelescope/stdatamodels/pull/86

However the feature seems to be unused with no schemas containing `deprecated_properties`.

This PR removes the unused feature.

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [x] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Review by hbushouse — COMMENTED** [review]
Code changes look fine to me. Have you run a full regression test of jwst against this PR?

**Comment by braingram** [comment]
> Code changes look fine to me. Have you run a full regression test of jwst against this PR?

Thanks for taking a look! I haven't run the regtests and will update this PR when I can queue them up.

**Comment by braingram** [comment]
Regression tests running at:
https://github.com/spacetelescope/RegressionTests/actions/runs/9484628685
As this is a GA run the expected failures (due to jenkins RHEL7 issues) can be seen:

**Review by hbushouse — APPROVED** [review]
Looks good.

**Pull request merged**
