### PR TITLE
JP-1713: fix `gentle_asarray` structured array handling and allow extra columns in datamodel schema

### PR DESCRIPTION
**Pull request by braingram**
This fixes issues with `gentle_asarray` handling of structured arrays (see #188) and adds support for allowing extra columns in tables defined in datamodel schema.

`gentle_asarray` is used when setting a data model property when the value is [_cast](https://github.com/spacetelescope/stdatamodels/blob/078bd1c504482f6d09118d2d240c449e4c71f99f/src/stdatamodels/properties.py#L82) to a dtype defined by the schema. ([Here](https://github.com/spacetelescope/stdatamodels/blob/078bd1c504482f6d09118d2d240c449e4c71f99f/src/stdatamodels/properties.py#L365) is one example from `properties.py` which includes several uses of `_cast` for `__setattr__`, `__setitem__` etc...).

Prior to this PR `gentle_asarray` mangled some dtypes when used with structured arrays (see #188 for more examples and details). For example,

```python
a = np.zeros(2, dtype=[('f', 'f8'), ('i', 'i4')])
ndt = np.dtype([('i', 'i4'), ('f', 'f8')])  # swap 'i' and 'f'
b = gentle_asarray(a, ndt)
assert b.dtype == ndt
assert ndt == np.dtype([('f', '<i4'), ('i', '<f8')]) # note that 'f' now has a 'i4' subdtype
```

This PR:
- reorganizes `gentle_asarray` by inverting some conditionals to allow removing nested if statements (to improve readability)
- reorganizes array columns using [merge_arrays](https://numpy.org/devdocs/user/basics.rec.html#numpy.lib.recfunctions.merge_arrays) when provided with input that has a dtype with columns in an order that does not match the schema
- calls [_safe_asanyarray](https://github.com/spacetelescope/stdatamodels/blob/078bd1c504482f6d09118d2d240c449e4c71f99f/src/stdatamodels/util.py#L91C5-L91C21) if sub-dtypes (dtypes for columns) differ (even if the difference is byte order, more on that below).
- adds an option `allow_extra_columns` to `gentle_asarray` to allow extra columns (which will be put at the end of the required columns) and exposes this option in the schema (see the oifits schema changes in this PR).

As mentioned above `_safe_asanyarray` is now used for byte order differences. Although fitsrec appears to ignore byte order differences for views (unlike normal structured arrays) this breaks down if a binary mask is applied to the fitsrec and can result in unexpected byte swaps and erroneous values.
```python
a = np.ones(3, dtype=[('a', '>f4'), ('b', '>f4')])
ndt = np.dtype([('a', '<f4'), ('b', '<f4')])
assert np.allclose(a.view(ndt)['a'], 4.6006e-41)  # bytes were correctly swapped
h = fits.HDUList()
h.append(fits.BinTableHDU())
h[-1].data = a
v = h[-1].data.view(ndt)  # this should swap the bytes
assert np.allclose(v['a'], 1.0)  # bytes were not correctly swapped
assert np.allclose(v[[True, False, False]]['a'], 4.6006e-41)  # applying a binary mask results in swapped bytes
```
@perrygreenfield I think this is another reason to remove all uses of fitsrec.

While working on this PR I discovered that the jwst miri cubepars reference files contain tables with columns in an order that do not match the schema (see #188). Prior to this PR, columns names but not dtypes were being swapped. This was not an issue in practice as the swapped columns have the same dtype. With this PR the names and dtypes are swapped (and tests were added for this and several other cases, see the new parametrized test in `test_util.py`).

This PR moves the single test `test_gentle_asarray` from `test_storage.py` into `test_util.py` and removes `test_storage.py`.

The changes in this PR will make [JP-1713](https://jira.stsci.edu/browse/JP-1713) easier to address as we won't need to make different oifits schemas for each file type (which have different, optional columns in some tables).

**Checklist**
- [ ] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Comment by braingram** [comment]
This will need a regression test run. I've tried to get an understandable one but I think I'm hitting differences due to #190 and https://github.com/spacetelescope/jwst/pull/7799.

The first run (with this PR) failed with 99 errors:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/847/tests
Scanning through them (I did not investigate every failure) they appear unrelated:
```
AssertionError: 
 fitsdiff: 5.3.1
 a: /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/test_outputs/popen-gw6/test_fgs_guider_run_guider_pipelines0/exptype_fgs_acq1_cal.fits
 b: /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/test_outputs/popen-gw6/test_fgs_guider_run_guider_pipelines0/truth/exptype_fgs_acq1_cal.fits
 HDU(s) not to be compared:
  ASDF
 Keyword(s) not to be compared:
  CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE NAXIS1 TFORM*
 Table column(s) not to be compared:
  CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE NAXIS1 TFORM*
 Maximum number of different data values to be reported: 10
 Relative tolerance: 1e-05, Absolute tolerance: 1e-07
Primary HDU:
   Headers contain differences:
     Keyword PRD_VER  has different comments:
        a> S&OC Project Reference Database (PRD) Version
        b> S&OC PRD version number used in data processing
     Keyword SDP_VER  has different comments:
        a> Data processing (DP) Software Version
         ?                 ^^^^^^        ^
        b> Data processing software version number
         ?                 ^        ^      +++++++
```
and look similar or the same to the errors for the run for #190 (which also had 99 errors):
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/843/tests

I tried making a branch with #190 reverted:
https://github.com/braingram/stdatamodels/tree/gentle_asarray_wo_190
and running regression tests against that branch:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/848/tests
However that one showed errors which look suspiciously like the truth files were updated to agree with #190.
```
AssertionError: 
 fitsdiff: 5.3.1
 a: /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/test_outputs/popen-gw13/test_fgs_guider_run_guider_pipelines0/exptype_fgs_acq1_cal.fits
 b: /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/test_outputs/popen-gw13/test_fgs_guider_run_guider_pipelines0/truth/exptype_fgs_acq1_cal.fits
 HDU(s) not to be compared:
  ASDF
 Keyword(s) not to be compared:
  CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE NAXIS1 TFORM*
 Table column(s) not to be compared:
  CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE NAXIS1 TFORM*
 Maximum number of different data values to be reported: 10
 Relative tolerance: 1e-05, Absolute tolerance: 1e-07
Primary HDU:
   Headers contain differences:
     Keyword PRD_VER  has different comments:
        a> S&OC PRD version number used in data processing
        b> S&OC Project Reference Database (PRD) Version
     Keyword SDP_VER  has different comments:
        a> Data processing software version number
         ?                 ^        ^      -------
        b> Data processing (DP) Software Version
         ?    
```

I did another run and see errors like the following:
```
ssertionError: 
   fitsdiff: 5.3.1
   a: /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/test_outputs/popen-gw31/test_miri_lrs_slit_spec2_run_pipeline0/jw01530005001_03103_00001_mirimage_pathloss.fits
   b: /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/test_outputs/popen-gw31/test_miri_lrs_slit_spec2_run_pipeline0/truth/jw01530005001_03103_00001_mirimage_pathloss.fits
   HDU(s) not to be compared:
    ASDF
   Keyword(s) not to be compared:
    CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE NAXIS1 TFORM*
   Table column(s) not to be compared:
    CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE NAXIS1 TFORM*
   Maximum number of different data values to be reported: 10
   Relative tolerance: 1e-05, Absolute tolerance: 1e-07
  
  Extension HDU 1 (SCI, 1):
  
     Data contains differences:
       Data differs at [304, 8]:
          a> 1.2934873
          b> 1.2930368
```
Which appear to be caused by: https://github.com/spacetelescope/jwst/pull/7799

@hbushouse any suggestion for running the regression tests against this PR? Is there an estimate for when the truth files will be updated for the core schema and other changes?

**Comment by braingram** [comment]
I ran another regression test run this morning and it had one failure:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/851/pipeline/202/
The failure `test_nircam_image_stages12[rate]` looks caused by a file not yet updated to comply with #190
```
E         Primary HDU:
E         
E            Headers contain differences:
E              Keyword OSS_VER  has different comments:
E                 a> Observatory Scheduling Software (OSS) Version
E                  ?                                       ^
E                 b> Observatory Scheduling Software (OSS) version n
E                  ?                                       ^      ++
```

**Comment by braingram** [comment]
@mcara @nden mentioned adding you as a reviewer for this package. Thanks in advance if you can take a look at this PR.

**Review by mcara — APPROVED** [review]
I think this is a great fix. Thanks!

**Comment by braingram** [comment]
> I think this is a great fix. Thanks!

Thanks for reviewing the changes!

**Pull request merged**
