### PR TITLE
add fits keywords to NRMModel schema

### LINKED ISSUE #359: NRMModel updates
Discussion originating on https://github.com/spacetelescope/stdatamodels/issues/342) with @braingram :

>I'm working on changing the AMI code to use values from the header of the NRM reference file rather than the hardcoded ones currently in [mask_definitions.py](https://github.com/spacetelescope/jwst/blob/main/jwst/ami/mask_definitions.py). When I load the reference file as an NRMModel, the keywords I need are in the extra_fits part of the tree, but instead of being [accessed like this](https://stdatamodels.readthedocs.io/en/latest/jwst/datamodels/models.html#extra-fits-keywords) they seem to be stored in nested lists and have to be accessed by their index [...] This whole issue may be irrelevant anyways; since these values will be important to the AMI code I was thinking it might make sense to have them be defined/required in the schema.

>The reference file keywords aren't listed in the keyword dictionary and are in different schemas in this package. Adding them to the schema is required to get them out of "extra_fits". Adding them will require picking an attribute name so feel free to suggest one (or we can just use the current variable names) in that issue.

We concluded the values we need should be added to the NRMModel schema and therefore the keyword dictionary. I will confirm with other AMI team members what we want to call the attribute names (if different from the current FITS keyword names).

### PR DESCRIPTION
**Pull request by braingram**
Closes #359

The NRM reference files contain FITS keywords useful to CAL.
https://jwst-crds.stsci.edu/browse/jwst_niriss_nrm_0001.fits

This PR adds those keywords to the schema so they are accessible via the datamodel interface:
- `model.flat_to_flat`
- `model.x_a1` etc...

Regression tests running at https://github.com/spacetelescope/RegressionTests/actions/runs/11802888443

## Tasks
- [ ] update or add relevant tests
- [ ] update relevant docstrings and / or `docs/` page
- [ ] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] [run `jwst` regression tests](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) with this branch installed (`"git+https://github.com/<fork>/stdatamodels@<branch>"`)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.feature.rst``: new feature
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.doc.rst``: documentation change
- ``changes/<PR#>.removal.rst``: deprecation or removal of public API
- ``changes/<PR#>.misc.rst``: infrastructure or miscellaneous change
</details>

### CODE REVIEW

**Comment by braingram** [comment]
> I think this looks good! To make sure I understand, these will not be accessed via the `meta` tree but rather from the "top level" of the datamodel? I.e. `model.x_a1` rather than `model.meta.x_a1`?

Exactly! Feel free to give it a try with the current NRM reference file (and this branch) if you're curious.

**Comment by rcooper295** [comment]
Thanks! I was able to try it with your branch and it looks good! I realized that there may be two additional keywords whose values are currently hardcoded but that we could read in from this model instead, but I need to confirm if they are actually the same as values we already have in the FITS header, and if so, what we should call the attributes. I should have an answer on that tomorrow.
(For more details, this is the message I sent the AMI team):

> mask_definitions.py contains:
> ```
> self.activeD = 6.559 * m  # webbpsf kwd DIAM  - not a 'circle including all holes'
> self.OD = 6.610645669291339 * m  # Full pupil file size, incl padding, webbpsf kwd PUPLDIAM
> ```
> while the NRM reference file currently contains:
> ```
> DIAM    =             6.559348 / Flat-to-flat distance across pupil in V3 axis  
> PUPLDIAM=             6.603464 / Full pupil file size, incl padding.            
> PUPL_CRC=             6.603464 / Circumscribing diameter for JWST primary
> ```      
> I'm not sure if `activeD` should be the same as `DIAM` (it is, at least up to the fourth decimal place) and if `OD` should be the same as `PUPLDIAM` (it isn't quite) but if these are referring to the same quantity we should probably make them consistent.

**Comment by braingram** [comment]
I'll mark this as draft until we hear back about the extra keywords.

**Comment by rcooper295** [comment]
I spoke to my AMI team members and chased down the source of these numbers (or what we should be using) and we'd like to add these two: 
```
 diameter:
      fits_keyword: DIAM
      title: "[m] Flat-to-flat distance across pupil in V3 axis"
pupil_circumscribed:
      fits_keyword: PUPL_CRC
      title: "[m] Circumscribing diameter for JWST primary"
```
Thanks for your patience!!

**Pull request merged**
